# -*- coding: utf-8 -*-

DEBUG = True
COOKIE_SECRET = '@COOKIE_SECRET@'
COOKIE_HOURS = 24 * 7
PASSWORD_SECRET = b'@PASSWORD_SECRET@'

REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB = 1

MYSQL_HOST = '127.0.0.1'
MYSQL_DB = '@MYSQL_DB@'
MYSQL_USER = '@MYSQL_USER@'
MYSQL_PWD = '@MYSQL_PWD@'
MYSQL_CHARSET = 'utf8mb4'
